### ISSUE TITLE
Nusmv in interactive mode

### ISSUE THREAD

**Issue by khrrzkrm** [badouralix/dockerfiles#6] opened 2020-12-09 14:05 UTC
Dear Badouralix,

The NUSMV official webpage is down, so it is  no longer possible to get the source file.

Your docker image works fine, except that the command:  docker run -it --rm -v $PWD:/input:ro badouralix/nusmv -int <file> does not really allows one to use Nusmv in interactive mode...

I'm  using the following command: docker run -it --rm -v ${PWD}:/input:ro   --entrypoint /bin/sh badouralix/nusmv -c /bin/ash
and then on the bash: nusmv -int <file name>.
The problem is that I get a segmentation fault for any possible command in interactive mode. (go, simulate , pick_state -i etc ...)

Do you think it is a Nusmv Bug , command error or a configuration error in the docker file?

Regard;

**Comment by badouralix** [comment] 2020-12-12 16:01
Hi @khrrzkrm !

Thanks for the feedback, this is an interesting problem indeed :thinking:

I have never tried the interactive mode, but I'll try to figure it out

**Comment by badouralix** [comment] 2021-11-01 22:01
Hi @khrrzkrm ! Is the segmentation fault still occurring on your side ?
I tried the interactive mode on a few examples from https://nusmv.fbk.eu/examples/examples.html, but couldn't reproduce the issue
Would you be able to provide a small example that exposes the problem ?

**Comment by badouralix** [comment] 2022-01-03 17:59
I'll go ahead and close the issue
Feel free to re-open it if the problem occurs again

**Closed as completed by badouralix** 2022-01-03 17:59 UTC
Labels: bug
